### ISSUE TITLE
After installing the theme, I can't get any searching results through the search form.  

### ISSUE THREAD

**Issue by liushuaikobe** [panks/fabric#10]
After I installing this theme, I try to search some articles by the search form on the top bar, only to find that no matter what key words I choose, it doesn't give me any results, and the progress control keeps rotating...

First I though the reason may be I chose some Chinese as the searching key words, however, English words don't make any sense. I'm sure all the words appear in my articles. 

It makes me upset a lot.

Is there some additional necessary configuration?

**Comment by panks** [comment]
Are you sure you added the value of 'tapir_token' in your _config.yml?

**Comment by liushuaikobe** [comment]
@panks what's that? I have done nothing about that~I search `tapir_token` in my _config.yml, and it doesn't appears.

**Comment by panks** [comment]
Read the 'Tapirgo Search' in README.md here: https://github.com/panks/fabric
You need to manually add it to your _config file and it's values is the token you get from the Tapirgo website.

**Comment by liushuaikobe** [comment]
@panks OK，thx a lot. Sorry for my reading doc carelessly!
