### ISSUE TITLE
Menu links shift down

### ISSUE THREAD

**Issue by lgiordani** [panks/fabric#3]
Hi, on FIrefox 18.0.2 under Ubuntu the links in the main menu (Home, Archives, Rss) shift some pixels down when the mouse is over. See the attached image.
Thank you

![Fabric_menu](https://f.cloud.github.com/assets/1675575/166892/d9031c0e-79b9-11e2-8739-cb2cd0fcd02e.png)

**Comment by panks** [comment]
It was actually meant for giving a 'button' like effect, but I guess it wasn't that apparent. Thanks for pointing it out. :)
