### ISSUE TITLE
Adding author information under posts

### ISSUE THREAD

**Issue by lgiordani** [panks/fabric#4]
Hi,

is it possible to have authorship added to posts? Something like "Posted by: <Author Name>" perhaps linked to the Google+ profile or to a custom page in the blog?

I noticed that there is a "source/_includes/post/author.html" template which is however included nowhere.

Thank you!

Leo

**Comment by panks** [comment]
Yeah sure it's possible. Modify `source/_includes/post/author.html` to suit your needs, by default it would pickup the author name from `_config.yml` which is in your Octopress directory and display it as `Posted by <author name>`. To add a G+ or custom page link replace `{{ author }}` with that link in author.html file.

To enable it just add `{% include post/author.html %}` after `{% include article.html %}` in your `source/_layouts/post.html` file which is in fabric directory.
Hope that answers your query. :)

**Comment by lgiordani** [comment]
Sure, thank you very much :)
