### ISSUE TITLE
Google Analytics and Webmaster Tools

### ISSUE THREAD

**Issue by lgiordani** [panks/fabric#6]
Hi,

while Google Analytics seems alright with the current Fabric inclusion of the JS snippet just after the footer

``` sh
source/_includes/after_footer.html:{% include google_analytics.html %}
```

Google Webmaster Tools keeps complaining that it should be in <head>, according to http://support.google.com/analytics/bin/answer.py?hl=en&answer=1008080 number 3 "Copy and place the code snippet".

I'm going to try moving the snippet to see if it works. However the current code does not work.

Thanks!

Leo

**Comment by lgiordani** [comment]
I can confirm that moving

```
{% include google_analytics.html %}
```

from `source/_includes/after_footer.html` to `source/_includes/head.html` just before the `</head>` closing tag works fine both with Google Analytics and Webmaster Tools.
Look at https://github.com/lgiordani/fabric/commit/ef04d8f4fbeb24d32601c66da74923f821866fe3

Sorry, I cannot send a pull request since I was changing other parts of the code and made a mess :(

**Comment by panks** [comment]
No problem, I'll fix it here.
Thanks a lot! :)
