### ISSUE TITLE
Post title word case

### ISSUE THREAD

**Issue by lgiordani** [panks/fabric#7]
Posts have different case in post page and in archives.

A post entitled "Error handling in Erlang - a primer" becomes "Error Handling in Erlang - a Primer" in the post page, and "Error handling in Erlang - a primer" in archives page.

I think this is unwanted. Thank you

**Comment by panks** [comment]
Thank you for the report. Now both of them would be consistent. If you want the title to be displayed as it is then set `titlecase` to `false` in _config.yml

**Comment by lgiordani** [comment]
A very fast fix (as always). Thank you very much!

Leonardo Giordani
Author of The Digital Cat http://lgiordani.github.com
My profile on About.me http://about.me/leonardo.giordani

2013/6/3 Pankaj notifications@github.com
